import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { formatCurrency, formatDate } from "@/lib/utils";
import type { Invoice } from "@/lib/data";

export function exportInvoicesPdf(invoices: Invoice[]) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.setTextColor(79, 70, 229);
  doc.text("VendorBridge", 14, 20);
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text("Invoice Report", 14, 28);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 34);
  doc.text(`Total records: ${invoices.length}`, 14, 40);

  autoTable(doc, {
    startY: 48,
    head: [["Invoice #", "Vendor", "Amount", "Due Date", "Status"]],
    body: invoices.map((inv) => [
      inv.invoiceNumber,
      inv.vendorName,
      formatCurrency(inv.amount),
      formatDate(inv.dueDate),
      inv.status,
    ]),
    headStyles: { fillColor: [79, 70, 229], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
  });

  doc.save("VendorBridge_Invoices.pdf");
}

export function exportInvoicesPdfProcurement(invoices: Invoice[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setFontSize(20);
  doc.setTextColor(79, 70, 229);
  doc.text("VendorBridge", 14, 22);
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text("Procurement Management Platform", 14, 30);
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59);
  doc.text("Invoice Report", 14, 40);
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 48);
  doc.text(`Total records: ${invoices.length}`, 14, 54);

  autoTable(doc, {
    startY: 62,
    head: [["Invoice #", "Vendor Name", "Amount", "Due Date", "Status"]],
    body: invoices.map((inv) => [
      inv.invoiceNumber,
      inv.vendorName,
      formatCurrency(inv.amount),
      formatDate(inv.dueDate),
      inv.status,
    ]),
    headStyles: { fillColor: [79, 70, 229], textColor: 255 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9, cellPadding: 4 },
    didDrawPage: () => {
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("Generated by VendorBridge", pageWidth / 2, pageHeight - 10, { align: "center" });
    },
  });

  doc.save("VendorBridge_Invoice_Report.pdf");
}

export function exportInvoicesCsv(
  invoices: Invoice[],
  filename = "VendorBridge_Invoices.csv"
) {
  const headers = ["Invoice Number", "Vendor Name", "Amount", "Due Date", "Status"];
  const rows = invoices.map((inv) => [
    inv.invoiceNumber,
    inv.vendorName,
    String(inv.amount),
    inv.dueDate,
    inv.status,
  ]);
  const csv = [headers, ...rows]
    .map((row) => row.map((c) => `"${c}"`).join(","))
    .join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
